name: msvc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { msvc: Visual Studio 17 2022, arch: x64, config: Release }

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Configure CMake
      run: |
        cmake -B build -G "${{ matrix.msvc }}" -A ${{ matrix.arch }}

    - name: Build
      run: cmake --build build --config ${{ matrix.config }}

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.config }} --output-on-failure
